### PR TITLE
Add support for new ReCaptcha beta

### PR DESCRIPTION
**Pull request by mfjordvald**
There is a new ReCaptcha API currently undergoing beta testing. This adds support for that API.

### CODE REVIEW

**Comment by romainneutron** [comment]
I'd rather prefer an adapter integration than a new method

**Comment by mfjordvald** [comment]
Sorry, don't have time to do it like that. We needed it for work so I made a quick fix for it and figured I'd contribute it in case you wanted it.

**Comment by barryvdh** [comment]
It seems to have simplified a bit and the new beta is now the default:
http://googleonlinesecurity.blogspot.nl/2014/12/are-you-robot-introducing-no-captcha.html
https://github.com/google/ReCAPTCHA
https://developers.google.com/recaptcha/docs/verify

**Comment by dmouse** [comment]
I'm using reCaptcha with the new version basically the change is the new field name "g-recaptcha-response" and the validation URL recaptcha/api/siteverify.

I can create another PR to resolve this issue or continue in this thread?

**Pull request closed without merging**
