### PR TITLE
[Proposal] Laravel 4 out of the box integration

### PR DESCRIPTION
**Pull request by rmobis**
Is there any chance we can add some integration for Laravel 4. It could be done without altering any of the already existing code, so it shouldn't really be a problem. More specifically, I'm talking about:
- **Facade:** For the static methods syntax.
- **Form Macro:** A simple form macro, for quick HTML output
- **Validation Rule:** Automatically check ReCaptcha using Laravel's Validator class
- **Configuration:** A configuration file that could be published and edited, with the private key, public key, etc...
- **Service Provider:** Ties everything else together.

If that's okey, I could work on a simple implementation.

Thanks.

### CODE REVIEW

**Comment by rmobis** [comment]
There ya go!
Added a simple test for the Validator class and a basic documentation about it on README.md.

**Comment by rmobis** [comment]
Removed shorthand arrays usage, so it doesn't break on PHP <= 5.3.

**Comment by romainneutron** [comment]
Thanks for your work !

Please PHP-CS-fix the PR with http://cs.sensiolabs.org/.
Does `src/views/recaptcha.blade.php` and `src/config/config.php` can be removed from the PR ? It could be added as examples of these files in the README.

**Comment by rmobis** [comment]
Well, theoretically, both files could be removed, but they'd both affect important parts of the functionality. `src/config/config.php` file, for instance, couldn't even be added as an example, because it wouldn't work, which would mean no easily setup configuration. Removing `src/views/recaptcha.blade.php` would take away Form Macro functionality and, even if added as an example, require a few more extra steps by the user. While still functional, the PR would pretty much lose its main point, which was an easy integration with Laravel.

I'll take a look at PHP-CS-fixing it later day.

**Comment by rmobis** [comment]
PHP-CS fixed.

**Comment by rmobis** [comment]
Is there anything missing on this PR or anything I could do to get it approved?
If you'd rather not merge, it's cool, I'm just asking because it's been a while without any response.

**Comment by eridal** [comment]
Hey there,
Seems this project was abandoned.
I'm [starting a fork](https://github.com/eridal/ReCaptcha), mostly because of my needs; do you want to join forces?

**Comment by rmobis** [comment]
Why not, @eridal?
I'll try and get a PR on that asap.

**Comment by romainneutron** [comment]
This project is not abandonned, I just want to avoid overload it with things I can not maintain by myself.

You should better create a laravel plugin/bundle/whatever it is named that use this library.
Compose with the library instead of extending it.

If you really want to fork, then fork. But avoid to violate the [license](https://github.com/romainneutron/ReCaptcha/blob/master/LICENSE), it's not fair

**Comment by eridal** [comment]
Hey there,

I forked the project just to remove all the noise it contained -- there was no point for it to include all those extra packages .. all that Silex, Symfony, blablah was too noisy for the project "_You should better create a laravel plugin/bundle/whatever it is named that use this library._" :smile:

Also I didn't change the license, [composer.json](https://github.com/eridal/ReCaptcha/blob/master/composer.json) says MIT and your name and email are still there. I removed the LICENSE file in a clean up, and like said before, will add it back

**Comment by romainneutron** [comment]
Why not decouple the ReCaptcha library from symfony/http-foundation and propose changes here ?

Yes, I do think a laravel plugin or a symfony bundle have not their place in this library as they require too much resources that should be maintained (assets and implementation).

I did not say that you changed the license, I said you violated it, it's different : the MIT license suppose you must keep my original license file whatever you do with my code.

**Comment by eridal** [comment]
yeah, sorry I understood this was a dead project.. look this PR took 7 months.. 7. months.

hold on, "decouple" you said? are we really talking about 25 lines taken from [google code](http://code.google.com/p/recaptcha/source/browse/trunk/recaptcha-plugins/php/recaptchalib.php#152)?? I even forked just to keep the reference to your project!!

**Comment by romainneutron** [comment]
coupling / decoupling is about separating concerns, dude. Google code is not testable, not mockable. Here, it is.

well. If you want to contribute, feel free

**Comment by rmobis** [comment]
@romainneutron, you could have mentioned that 7 months ago, when I first proposed the feature.
That's fine, though, it will work on a separate package.

Thanks.

**Pull request closed without merging**
